name: conftest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - name: install conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.23.0/conftest_0.23.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.23.0_Linux_x86_64.tar.gz
          mkdir -p $HOME/.local/bin
          mv conftest $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: checkout code
        uses: actions/checkout@v2

      - name: validate
        run: |
          conftest verify policy
